### ISSUE TITLE
When mailgun (eventual recipient) rejects an email, the response isn't serialized properly

### ISSUE THREAD

**Issue by bradrust** [outr/mailgun4s#15]
Sent an email which was rejected by the intended recipients provider.   The response from mailgun API's appears to be containing "404.0" which is apparently being sent as a Json number.   If this defect just doesn't have enough details, I can try to replicate. 

`java.lang.RuntimeException: 404.0 is a Num, not a Obj
    at fabric.Value.asValue(Value.scala:181)
    at fabric.Value.asValue$(Value.scala:178)
    at fabric.Num.asValue(Value.scala:420)
    at fabric.Value.asObj(Value.scala:200)
    at fabric.Value.asObj$(Value.scala:200)
    at fabric.Num.asObj(Value.scala:420)
    at fabric.rw.ClassW.write(ClassW.scala:8)
    at fabric.rw.ClassW.write$(ClassW.scala:8)
    at org.matthicks.mailgun.MessageResponse$$anon$1$$anon$3.write(MessageResponse.scala:8)
    at org.matthicks.mailgun.MessageResponse$$anon$1.write(MessageResponse.scala:8)
    at org.matthicks.mailgun.MessageResponse$$anon$1.write(MessageResponse.scala:8)
    at fabric.rw.package$Asable.as(package.scala:11)
    at org.matthicks.mailgun.Mailgun.$anonfun$send$17(Mailgun.scala:106)`

**Comment by darkfrog26** [comment]
Ah, appears to be an old bug in Fabric. This is solved in the latest version, so I think I just need to update the dependency and do another release.

**Comment by darkfrog26** [comment]
I just released version `1.1.0` which should resolve this. Please note, that this update migrates from using `Future` to cats-effect's `IO`, so some changes will likely be necessary to your code.
