### ISSUE TITLE
issue with gradle and "org.matthicks:mailgun4s_2.11:1.0.9"

### ISSUE THREAD

**Issue by Arnold1** [outr/mailgun4s#5]
Hi,

I use gradle to build and use the following dependency: "org.matthicks:mailgun4s_2.11:1.0.9"

i use scala 2.11.11
and added the following dependencies:
"org.scala-lang:scala-library:2.11.11",
"org.matthicks:mailgun4s_2.11:1.0.9"

how when i include "org.matthicks:mailgun4s_2.11:1.0.9" with a basic sendEmail i get the following error in some other code:
error: object Source is not a member of package io
```
io.Source.fromFile(file).getLines
```

**Comment by darkfrog26** [comment]
You're referencing `https://www.scala-lang.org/api/2.11.8/index.html#scala.io.Source`, so try just prefixing with `scala.io.Source` instead and see if that fixes it.  It probably has to do with imports you're making confusing the package `io`.

**Comment by Arnold1** [comment]
wow, that fixes it :D thanks so much. mailgun4s_2.11 is for scala 2.11?

have you measured how long it takes to send the email? and is it possible to send the email to multiple people?

**Comment by darkfrog26** [comment]
Yes, that's the dependency for 2.11.  If you are using 2.12 there is a dependency for it as well (http://search.maven.org/#search%7Cga%7C1%7Cmailgun4s).

Currently there's not a simple method to send to multiple recipients (unless you don't mind them being included in the "to" field).  You can always just create the `Message` and, since it's a case class, use `copy` to replace the `to` field and send each.

Something like this:

```scala
val mailgun: Mailgun = ...
val message: Message = ...
val recipients: List[EmailAddress] = ...
val futures: Future[List[MessageResponse]] = Future.sequence(recipients.map { recipient =>
  mailgun.send(message.copy(to = List(recipient))
})
```

This is all off the top of my head, so it's possible there are some syntactical issues, but it should get you going the right direction.

**Comment by Arnold1** [comment]
i run into an issue, any idea whats wrong?

```
package com.sendmail

import org.matthicks.mailgun._
import java.io._
import scala.concurrent._
import scala.concurrent.duration._

object HelloWorldMain {
	def main(args: Array[String]): Unit = {
		println("Hello World")

		val mailgun = new Mailgun("samples.mailgun.org", "api:key-xxxxxxxxxxxx")
		val response = mailgun.send(Message.simple(
      		    from = EmailAddress("postmaster@sandboxdxxxxxxxxx.mailgun.org", "Mailgun Sandbox"),
      		    to = EmailAddress("geri123456@gmail.com", "Geri"),
      		    "Mailgun4s Rules!",
      		    text = "This is the testing text"
    	        ))

		val result = Await.result(response, Duration.Inf)
		println(s"Result: $result")
	}
}
```

```
scala build/libs/sendmail-1.0-all.jar
Hello World
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
	at scribe.formatter.FormatterBuilder$.abbreviate(FormatterBuilder.scala:64)
	at scribe.formatter.FormatterBuilder$$anonfun$positionAbbreviated$1.apply(FormatterBuilder.scala:40)
	at scribe.formatter.FormatterBuilder$$anonfun$positionAbbreviated$1.apply(FormatterBuilder.scala:38)
	at scribe.formatter.FormatterBuilder$$anonfun$format$1.apply(FormatterBuilder.scala:57)
	at scribe.formatter.FormatterBuilder$$anonfun$format$1.apply(FormatterBuilder.scala:57)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at scribe.formatter.FormatterBuilder.format(FormatterBuilder.scala:57)
	at scribe.writer.ConsoleWriter$.write(ConsoleWriter.scala:8)
	at scribe.StandardLogHandler.publish(LogHandler.scala:20)
	at scribe.LogHandler$class.log(LogHandler.scala:10)
	at scribe.StandardLogHandler.log(LogHandler.scala:18)
	at scribe.LoggerSupport$$anonfun$log$1.apply(LoggerSupport.scala:74)
	at scribe.LoggerSupport$$anonfun$log$1.apply(LoggerSupport.scala:74)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at scribe.LoggerSupport$class.log(LoggerSupport.scala:74)
	at scribe.Logger.log(Logger.scala:16)
	at scribe.LoggerSupport$$anonfun$log$2.apply(LoggerSupport.scala:75)
	at scribe.LoggerSupport$$anonfun$log$2.apply(LoggerSupport.scala:75)
	at scala.Option.foreach(Option.scala:257)
	at scribe.LoggerSupport$class.log(LoggerSupport.scala:75)
	at scribe.package$.log(package.scala:3)
	at scribe.LoggerSupport$class.log(LoggerSupport.scala:70)
	at scribe.package$.log(package.scala:3)
	at io.youi.net.URL$.get(URL.scala:167)
	at io.youi.net.URL$.apply(URL.scala:123)
	at io.youi.net.URL$.apply(URL.scala:119)
	at org.matthicks.mailgun.Mailgun.<init>(Mailgun.scala:23)
	at com.sendmail.HelloWorldMain$.main(main.scala:12)
	at com.sendmail.HelloWorldMain.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:98)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:32)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:30)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:129)
	at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:98)
	at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:90)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:129)
	at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:22)
	at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:21)
	at scala.tools.nsc.JarRunner$.run(MainGenericRunner.scala:14)
	at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:28)
	at scala.tools.nsc.JarRunner$.runAndCatch(MainGenericRunner.scala:14)
	at scala.tools.nsc.JarRunner$.runJar(MainGenericRunner.scala:26)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:72)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:85)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:101)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

it seems to crash here:
```val mailgun = new Mailgun("samples.mailgun.org", "api:key-xxxxxxxxxxxx")```

**Comment by darkfrog26** [comment]
Looks like you're trying to use a version of `mailgun4s` or, more specifically `scribe` for a different version of Scala than you're actually using.

**Comment by Arnold1** [comment]
here my build.gradle, does that help to locate the issue?
```
plugins {
  id 'com.github.johnrengelman.shadow' version '2.0.1'
  id "com.github.maiflai.scalatest" version "0.16"
}

allprojects {
  repositories {
    mavenLocal()
    mavenCentral()
  }

  sourceCompatibility = 1.8
  targetCompatibility = 1.8
}

apply plugin: 'scala'
apply plugin: 'application'

mainClassName = "com.sendmail.HelloWorldMain"

version = "1.0"

ext {
  scala_full_version = '2.11.11'
  versions = [
    scala_full: scala_full_version,
    scala: scala_full_version.tokenize('.').dropRight(1).join('.'),
    mailgun4s: '1.0.9'
  ]
}

dependencies {
  compile (
    "org.scala-lang:scala-library:$versions.scala_full",
    "org.matthicks:mailgun4s_2.11:$versions.mailgun4s"
  )
}

shadowJar {
  manifest {
    attributes "Implementation-Title": "sendMail",
               "Implementation-Version": version
  }
  zip64 true
  baseName "sendmail"
}
```

**Comment by darkfrog26** [comment]
Sorry, I'm not a fan of Gradle or Groovy, so I'm not sure how much help I can be.  Why are you using 2.11 instead of 2.12 though?

**Comment by Arnold1** [comment]
result with scala2.12, whats forbidden??
```
$ scala build/libs/cla-1.0-all.jar 
Hello World
java.lang.RuntimeException: Failed to parse JSON response: Forbidden
	at org.matthicks.mailgun.Mailgun.$anonfun$send$16(Mailgun.scala:110)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: io.circe.ParsingFailure: expected json value got F (line 1, column 1)
```

build.gradle:
```
plugins {
  id 'com.github.johnrengelman.shadow' version '2.0.1'
  id "com.github.maiflai.scalatest" version "0.16"
}

allprojects {
  repositories {
    mavenLocal()
    mavenCentral()
  }

  sourceCompatibility = 1.8
  targetCompatibility = 1.8
}

apply plugin: 'scala'
apply plugin: 'application'

mainClassName = "com.sendmail.HelloWorldMain"

version = "1.0"

ext {
  scala_full_version = '2.12'
  versions = [
    scala_full: scala_full_version,
    scala: scala_full_version.tokenize('.').dropRight(1).join('.'),
    mailgun4s: '1.0.9'
  ]
}

dependencies {
  compile (
    "org.scala-lang:scala-library:$versions.scala_full",
    "org.matthicks:mailgun4s_2.12:$versions.mailgun4s"
  )
}

shadowJar {
  manifest {
    attributes "Implementation-Title": "sendMail",
               "Implementation-Version": version
  }
  zip64 true
  baseName "sendmail"
}
```

**Comment by Arnold1** [comment]
ok fixed it by changing removing api in front of the key and using a correct domain:
```
// domain and key is changed for security reason:
val mailgun = new Mailgun("sandboxd1bf610a341cc2e6c30ced4f853e.mailgun.org", "key-2bbe234ccc7053243242d99532a4cdfgfa")
```

output:
```
$ scala build/libs/cla-1.0-all.jar 
Hello World
Result: MessageResponse(<20171024014952.129070@sandboxd1bf610a395c41cc82e6c30ced4f853e.mailgun.org>,Queued. Thank you.)
```

the issue i notice now is that the main does not return....is that expected?

**Comment by darkfrog26** [comment]
Make sure you dispose the client when you're done:

```scala
mailgun.dispose()
```

https://github.com/outr/mailgun4s/blob/master/src/main/scala/org/matthicks/mailgun/Mailgun.scala#L122

**Comment by Arnold1** [comment]
oh yeah, now it works :) thanks so much... 

any idea why only mailgun4s_2.12 works for me?

**Comment by darkfrog26** [comment]
It's possible that something in your build setup is overriding and setting to 2.12 in your build?  Honestly, I have no idea though.  You should really consider switching to SBT and you'll lead a happier life.

**Comment by Arnold1** [comment]
ok will check, thanks for the help :)
